from pathlib import Path
from PIL import Image,ImageDraw,ImageFont
import json,html
r=Path(__file__).resolve().parents[1];m=json.loads((r/'manifest.json').read_text());f=ImageFont.truetype('/System/Library/Fonts/Supplemental/Arial.ttf',18)
items=[x for x in m if not x['file'].startswith('continuity/')];sheet=Image.new('RGB',(1800,((len(items)+5)//6)*460),'#10191d');d=ImageDraw.Draw(sheet)
for i,x in enumerate(items):
 im=Image.open(r/x['file']).convert('RGBA');im.thumbnail((270,400));xx=i%6*300+(300-im.width)//2;yy=i//6*460;sheet.paste(im,(xx,yy),im);d.text((i%6*300+10,yy+410),Path(x['file']).stem[:26],font=f,fill='#F2E5C8')
sheet.save(r/'ASSET-OVERVIEW.jpg')
p='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>LOSE THE TAIL / Production materials</title><style>
*{box-sizing:border-box}body{margin:0;background:#10191d;color:#f2e5c8;font:16px/1.5 Arial,sans-serif}a{color:inherit}header{padding:22px 5%;border-bottom:1px solid #344442;display:flex;justify-content:space-between;gap:20px;font:12px monospace;letter-spacing:2px}header b{color:#f2b84b}main{max-width:1450px;margin:auto;padding:40px 5%}h1{font-size:clamp(40px,6vw,84px);line-height:1;letter-spacing:-3px;max-width:800px;margin:26px 0}h2{font-size:30px;margin:50px 0 22px}.eyebrow{font:12px monospace;letter-spacing:3px;color:#f2b84b}.intro{max-width:680px;color:#a9b0a6;font-size:18px}.actions{display:flex;gap:14px;flex-wrap:wrap;margin:28px 0 40px}.actions a{padding:14px 20px;border:1px solid #57635b;text-decoration:none}.actions a:first-child{background:#f2b84b;color:#10191d;font-weight:bold;border-color:#f2b84b}.hero{display:grid;grid-template-columns:1.7fr 1fr;gap:20px}.hero img{width:100%;display:block;border:1px solid #364641}.heroaside{display:grid;gap:20px}.filters{display:flex;gap:10px;flex-wrap:wrap;margin:35px 0 24px}button{font:14px Arial;color:#bcc6ba;border:1px solid #42544c;background:transparent;padding:10px 18px;cursor:pointer}button[aria-pressed=true]{background:#f2b84b;color:#10191d;border-color:#f2b84b}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:28px 20px}article{min-width:0}article img{width:100%;height:390px;object-fit:contain;background:#0b1215;border:1px solid #2c3b39}article[data-category=monitors],article[data-category=cards]{grid-column:span 2}article[data-category=monitors] img,article[data-category=cards] img{height:auto;aspect-ratio:16/9}article h3{font-size:17px;margin:12px 0 3px}article p{font:12px monospace;color:#9aa798;margin:0 0 8px}article a{font-size:13px;text-decoration:none;color:#f2b84b}article[hidden]{display:none}footer{padding:50px 0;color:#a9b0a6;border-top:1px solid #344442;margin-top:60px}audio{width:min(100%,650px)}@media(max-width:750px){.hero{grid-template-columns:1fr}.grid{grid-template-columns:repeat(2,minmax(0,1fr))}article img{height:310px}.heroaside{grid-template-columns:1fr 1fr}h1{letter-spacing:-1px}}</style>
<header><b>LOSE THE TAIL</b><span>PRODUCTION KIT / VOXEL NOIR / V2</span></header><main><div class="eyebrow">THREE LIVES. TWO DEATHS. ONE BREAKFAST.</div><h1>The city has a memory.</h1><p class="intro">A worn personal terminal. A surveillance desk that knows too much. One more chance to get it right. Rebuilt graphics for the 90-second trailer.</p><div class="actions"><a href="../LOSE-THE-TAIL-PRODUCTION-KIT-V2.zip">Download the rebuilt pack</a><a href="START-HERE.md">Shot-by-shot upload guide</a><a href="VIDEO-PROMPTS-VISIBLE-SCREENS.md">Video prompts</a></div><div class="hero"><img src="cards/03-end-card.png?v=2" alt="Pixel title above a city silhouette"><div class="heroaside"><img src="monitors/01-public-clue.png?v=2" alt="Villain surveillance desk"><img src="cards/02-you-died-again.png?v=2" alt="Second death card"></div></div><h2>Choose your scene materials.</h2><p class="intro">Amber = public route. Mint = shielded route. White = Zero’s guided shielding sequence. Rust = exposed information. Open an image to inspect it at full resolution.</p><nav class="filters" aria-label="Filter materials">'''
for key,label in [('all','All materials'),('screens','Phone screens'),('monitors','Gang monitors'),('cards','Death + title'),('branding','Branding'),('continuity','Continuity')]:p+=f'<button type="button" data-filter="{key}" aria-pressed="{str(key=="all").lower()}">{label}</button>'
p+='</nav><section class="grid">'
for x in m:
 cat=x['file'].split('/')[0];p+=f'<article data-category="{cat}"><a href="{x["file"]}" target="_blank"><img loading="lazy" src="{x["file"]}?v=2" alt="{html.escape(x["description"])}"></a><h3>{html.escape(x["description"])}</h3><p>{", ".join(x["shots"]) or "CONTINUITY REFERENCE"}</p><a href="{x["file"]}" download>Download PNG ↗</a></article>'
for f in (r/'branding').glob('zcash*.png'):p+=f'<article data-category="branding"><a href="branding/{f.name}" download><img src="branding/{f.name}" alt="Official Zcash logo">Official Zcash / download</a></article>'
p+='''</section><footer><h2>Listen to the cast.</h2><p>Needle’s sarcastic pursuit. Zero’s deep, authoritative guidance.</p><audio controls src="audio/LOSE-THE-TAIL-90S-VOICE-PREVIEW-V3.mp3"></audio><p>21 wallet states · 3 case monitors · death and title cards · character references · original voice clips.<br>Screen text may still require the supplied PNG overlay if the video model distorts lettering.</p></footer></main><script>document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelectorAll('[data-category]').forEach(x=>x.hidden=b.dataset.filter!=='all'&&x.dataset.category!==b.dataset.filter)}));</script></html>'''
(r/'index.html').write_text(p)
print('Gallery and overview refreshed')
